conditioning:
  method: diss_ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ../../data/text/images

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [138, 139]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256
    mask_loc: !!python/tuple [50, 65]


  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/text/additional_texts'
    scale: 0

search_algorithm:
  name: group-meeting
  base: 50
  min_group: 2
  max_group: 2
  start_step: 800

num_particles: 2
