conditioning:
  method: diss_ps
  params:
    scale: 0.9

data:
  name: ffhq
  root: ../../data/text/images

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 32

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/text/additional_texts'
    scale: 0

search_algorithm:
  name: group-meeting
  base: 50
  min_group: 2
  max_group: 4
  start_step: 800

num_particles: 4
