conditioning:
  method: diss_ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ../../data/vishnu_images/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./diffusion-posterior-sampling/bkse/options/generate_blur/default.yml

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/gpt_texts'
    scale: 16 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 100
  min_group: 2
  max_group: 4
  start_step: 960

num_particles: 4
