conditioning:
  method: diss_ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ../../data/vishnu_images/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [138, 139]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/gpt_texts'
    scale: 0.1 # the scale for gradient

search_algorithm:
  name: group-meeting
  base: 8
  min_group: 2
  max_group: 4
  start_step: 900

num_particles: 4
