conditioning:
  method: diss_ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ../../data/vishnu_images/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/gpt_texts'
    scale: 0.3 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 4000
  min_group: 4
  max_group: 4

num_particles: 4
