conditioning:
  method: diss_ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ../../data/images/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: adaface
    steering: [search]
    data_path: '../../data/additional_images'
    scale: 16 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 2000
  min_group: 1
  max_group: 1

num_particles: 1
