conditioning:
  method: diss_ps
  params:
    scale: 0.9

data:
  name: ffhq
  root: ../../data/vishnu_images/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 32

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: text-alignment
    steering: [search]
    data_path: '../../data/gpt_texts'
    scale: 16 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 200
  min_group: 4
  max_group: 4

num_particles: 4
