conditioning:
  method: diss_ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ../../data/images/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: adaface
    steering: [search]
    data_path: '../../data/additional_images'
    scale: 16 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 4000
  min_group: 1
  max_group: 1

num_particles: 1
