conditioning:
  method: diss_ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ../../data/faceID/images/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: adaface
    steering: [search]
    data_path: '../../data/faceID/additional_images'
    scale: 0.6

search_algorithm:
  name: group-meeting
  base: 4
  min_group: 2
  max_group: 8

num_particles: 8
