conditioning:
  method: mpgd_wo_proj
  params:
    scale: 4

data:
  name: ffhq
  root: ../../data/images/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 6

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: adaface
    steering: [search]
    data_path: '../../data/additional_images'
    scale: 1.0 # the scale for gradient in MCMC steps

search_algorithm:
  name: group-meeting
  base: 2
  min_group: 2
  max_group: 8

num_particles: 8
