conditioning:
  method: mpgd_wo_proj
  params:
    scale: 10 # will be changed in another script

data:
  name: ffhq
  root: ./data/samples

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5
  
  noise: 
    name: gaussian
    sigma: 0.05
